# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties
# You can find the latest versions here: https://projects.neoforged.net/neoforged/neoforge
# The Minecraft version must agree with the Neo version to get a valid artifact
minecraft_version=26.3
minecraft_version_range=[26.3]
neo_version=26.3.0.42-beta

## Mod Properties
mod_id=tales_of_the_verdant_wind
mod_name=Tales of The Verdant Wind
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=cliffordha.totvw

## Dependencies
terrablender_version=26.3.0.0.9
terrablender_version_range=[26.3.0.0.9]
cloth_config_version=[26.3.159]
